### ISSUE TITLE
Nginx container missing

### ISSUE THREAD

**Issue by michield** [ksylvan/docker-mail-server#13]
https://github.com/ksylvan/docker-mail-server/blob/a8ed746802d25fae3bab3a3b57b2395419a209c0/roles/mailserver/files/docker-compose.yml#L175

This container image no longer exists: https://hub.docker.com/u/wonderfall

**Comment by michield** [comment]
I've run a build on https://github.com/Wonderfall/dockerfiles/tree/master/boring-nginx

and pushed it to https://hub.docker.com/r/phplist1/boring-nginx

**Comment by ksylvan** [comment]
Thank you for this.

**Comment by ksylvan** [comment]
Fixed in https://github.com/ksylvan/docker-mail-server/commit/658b851af45a618729473e80509ac7c87a0c08cd
