### ISSUE TITLE
ERROR! 'name' is not a valid attribute for a Block

### ISSUE THREAD

**Issue by ghost** [ksylvan/docker-mail-server#5]
ansible-playbook  -u  deploy mailserver.yml
ERROR! 'name' is not a valid attribute for a Block

The error appears to have been in '/home/dingo/docker-mail-server/roles/mailserver/tasks/main.yml': line 118, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Set up the contact_form_postfix
  ^ here

**Comment by ghost** [comment]
sudo pip install ansible --upgrade

**Comment by ksylvan** [comment]
Thanks.
